### ISSUE TITLE
Fix example hatari command

### ISSUE THREAD

**Issue by danboid** [EmmanuelKasper/mck#3]
I presume that you are the webmaster for https://subsole.org/st_mint ?

The example hatari command given on that page doesn't work because it has missed out the `-s 4` (FM needs at least 4MB RAM) and `-m` options to enable mono video output. So, the full command to use is:

```
hatari -s 4 -m --acsi st_mint-1.4.img
```

I've not actually used FreeMiNT yet, I'm currently trying to get it to boot via a sidecart on my 4 MB STFM but no luck just yet. It might just be case of getting EmuTOS to start in mono mode like I had to do with hatari?

Thanks

**Comment by EmmanuelKasper** [comment]
Thanks for the report, I fixed the hatari command line in https://subsole.org/st_mint  .
On a real ST remember the monitor has to be a hardware monochrome monitor, SM124 or the like, or use the proper adapter cable to a monitor which can do 640*480 @72Hz.
If having issues, please use the FreeMint part of the atari forum at https://www.atari-forum.com/viewforum.php?f=126

**Comment by danboid** [comment]
Do you think I should be able to run mint gcc and build some small C programs under Mint with only 4 MB RAM?

I'll want at least make as well, ofc.

**Comment by danboid** [comment]
I will open another ticket re partitions.
